name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.2.0
homepage: https://github.com/simolus3/web3dart

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # code generation for contracts, shouldn't be imported outside of lib/src/builder/
  build: ^2.0.0
  build_config: ^1.0.0
  dart_style: ^2.0.0
  code_builder: ^4.0.0
  path: ^1.8.0

  pointycastle: ^3.0.1
  convert: ^3.0.0
  meta: ^1.1.0
  http: ^0.13.0
  js: ^0.6.3
  uuid: ^3.0.1
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0
  collection: ^1.14.11

dev_dependencies:
  build_runner: ^2.0.3
  build_test: ^2.1.0
  web_socket_channel: ^2.0.0
  test: ^1.9.0
  coverage: ^1.0.1
